### ISSUE TITLE
it is not working with latest bootstrap,

### ISSUE THREAD

**Issue by Rak-** [eureka2/ab-datepicker#36]
it is not working with latest bootstrap 4.1.3 , getting alignment issues for top bar

**Comment by maddya** [comment]
I had a similar issue using older version of bootstrap (v3.3.5) - my calendar control wasn't aligning correctly with my input box. I had to wrap my label and input elements in a div with "input-group" class. I tried this because that class appears to be used to look up parent elements in the datepicker.js source code. Also note that a label element with a for attribute matching the input element's id is also required.

Here's a super simplified version of the HTML changes I described:

```
<div class="input-group">
    <label for="date-picker" >Label</label>
    <input id="date-picker" type="text"/>
</div>
```

**Comment by omarkasem** [comment]
Same here

**Comment by gburghardt** [comment]
I ran into issues with Bootstrap 3.3.X as well. Seems like things only positioned well when putting the date picker inside a `form-group` and `col-x-n` element, e.g.

```html
<div class="form-group">
    <label for="..." class="control-label col-md-3">Foo</label>
    <div class="col-md-9">
        <input type="text" ...>
    </div>
</div>
```

I just submitted a [pull request 41](https://github.com/eureka2/ab-datepicker/pull/41) to resolve some general positioning issues. Basically in the `DatePicker#show` method we need to align the date picker to the left side of the text input, rather than trying to calculate the width of the label. This should also resolve the issue brought up by @maddya, which requires the input field to have a corresponding `<label>` element with a `for` attribute. The `for` attribute is not required, nor is the `<label>` element required as well. All of these are valid HTML, and accessible:

```html
<label>
    Label Text
    <input type="text">
</label>

<label for="foo">
    Label Text
</label>
<input type="text" id="foo">

<input type="text" id="foo" aria-label="Label Text">
```
