### ISSUE TITLE
Using TAB to navigate datepicker

### ISSUE THREAD

**Issue by tmorehouse** [eureka2/ab-datepicker#7]
The user should be able to navigate between the header controls and the calendar grid by using `tab`/`shift-tab`.

Currently tab closes the control.

**Comment by eureka2** [comment]
Take a look here : https://www.w3.org/TR/2015/WD-wai-aria-practices-1.1-20150514/#datepicker

> Tab - Like other widgets, the date picker widget receives focus by tabbing into it. Once focus is received, focus is repositioned on today's date in a grid of days and weeks. A second tab will take the user out of the date picker widget. Focus initially is placed on today's date.
> Shift+Tab - reverses the direction of the tab order. Once in the widget, a Shift+Tab will take the user to the previous focusable element in the tab order.

**Comment by tmorehouse** [comment]
In the demo, pressing tab or shift tab closes the datepicker.  It is impossible, with the current keyboard navigation, to tab to the datepicker's header controls (month select, previous, next), making them inaccessible to screen readers or keyboard only users.

See http://www.oaa-accessibility.org/examplep/datepicker1/ for an example of tab handling.

**Comment by eureka2** [comment]
I know perfectly this example because this datepicker is based on it (see the README). However, it is no longer in conformity with the "Fundamental Keyboard Navigation Conventions" of the W3C/WAI. Please read the third paragraph of chapter 4.1 of this document : https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/#kbd_generalnav
I agree with you, the datepicker's header controls are not directly accessible with the keyboard. However, actually, month can be changed with PgUp and PgDn, year with Ctrl+PgUp and Ctrl+PgDn.
We need to find other keys than tab to access these controls.

Sorry for my english.

Best regards.
